#ifndef HVTOOL_H
#define HVTOOL_H

enum HVTOOL_CONTAINER_OPERATIONS
{
    HVTOOL_KILL_CONTAINER = 0,
    HVTOOL_PAUSE_CONTAINER,
    HVTOOL_RESUME_CONTAINER,
    HVTOOL_SHUTDOWN_CONTAINER
};

HRESULT WINAPI ContainerUtility(PWSTR VmId, enum HVTOOL_CONTAINER_OPERATIONS Operation);
HRESULT WINAPI ListContainers(void);
HRESULT WINAPI ListEndpoints(void);
HRESULT WINAPI ListNetworks(void);
HRESULT WINAPI GetWslIP(BOOLEAN Verbose);

#endif /* HVTOOL_H */
